/**
 * 工作台二级功能 → Skill 1:1 目录
 * 一级：品牌设计 / 文案 / 视频 / 调研 / 模版 / 仓库
 * 二级：左栏功能及同栏内互斥管线（IP 创新/扩展、活动文生图/图生图、商拍换底模式、店招渠道、大片步骤等）
 */
import type { SkillDef, SpecialistId, ToolName } from "../types";

function tools(exits: Array<"propose" | "generate">): ToolName[] {
  const t: ToolName[] = ["memory_read", "memory_write"];
  if (exits.includes("propose")) t.push("propose");
  if (exits.includes("generate")) t.push("generate");
  return t;
}

function wb(view: string, sub?: string, extra?: string) {
  let href = sub ? `/${view}?sub=${sub}` : `/${view}`;
  if (extra) href += (href.includes("?") ? "&" : "?") + extra;
  return { view, sub, href };
}

/** 全部内置 Skill（每个二级功能一条） */
export const SKILL_CATALOG: SkillDef[] = [
  // ═══════════════════ 品牌设计 /image ═══════════════════
  {
    id: "skill.image.ip",
    name: "IP · 创新设计",
    description: "从零创作 IP/吉祥物：填槽 → 方向策划 → ip-propose → ip 出图",
    specialistId: "image.ip",
    workbench: wb("image", "ip"),
    triggerKeywords: ["ip", "IP", "吉祥物", "形象", "拟人", "创新设计"],
    requiredSlotKeys: ["creativeDesc", "colors"],
    exits: ["propose", "generate"],
    gatePolicy: "direction_plan",
    tools: tools(["propose", "generate"]),
    proposeScene: "ip-propose",
    generateScene: "ip",
    output: "image",
    steps: ["clarify", "propose", "confirm_plan", "generate ip"],
    isDefault: true,
  },
  {
    id: "skill.image.ip_extend",
    name: "IP · 扩展设计",
    description: "已有 IP 图延展视角/场景/动作：须参考图 → 图生图",
    specialistId: "image.ip",
    workbench: wb("image", "ip"),
    triggerKeywords: ["IP扩展", "扩展设计", "延展形象"],
    requiredSlotKeys: ["extendType"],
    exits: ["generate"],
    gatePolicy: "ref_image",
    tools: tools(["generate"]),
    generateScene: "ip",
    output: "image",
    steps: ["上传参考图", "选延展", "generate"],
    when: { slot: "mode", equals: "扩展设计" },
  },
  {
    id: "skill.image.ip_story",
    name: "IP · IP故事",
    description: "基于 IP 设定生成品牌故事文案",
    specialistId: "image.ip",
    workbench: wb("image", "ip"),
    triggerKeywords: ["IP故事", "形象故事", "人设故事"],
    requiredSlotKeys: [],
    exits: ["generate"],
    gatePolicy: "none",
    tools: tools(["generate"]),
    generateScene: "ip-story",
    output: "text",
    steps: ["读取设定", "generate ip-story"],
  },
  {
    id: "skill.image.vi_extend",
    name: "IP/Logo · VI延展",
    description: "主视觉确认后生成 VI 物料延展示意",
    specialistId: "image.ip",
    workbench: wb("image", "ip"),
    triggerKeywords: ["VI", "延展", "物料", "视觉识别"],
    requiredSlotKeys: [],
    exits: ["generate"],
    gatePolicy: "none",
    tools: tools(["generate"]),
    generateScene: "t2i-associate",
    output: "image",
    steps: ["generate VI 延展"],
  },
  {
    id: "skill.image.logo",
    name: "Logo 设计",
    description: "品牌 Logo：品牌名/风格齐后方向策划再出概念图",
    specialistId: "image.logo",
    workbench: wb("image", "logo"),
    triggerKeywords: ["logo", "Logo", "标志", "商标"],
    requiredSlotKeys: ["brandName"],
    exits: ["propose", "generate"],
    gatePolicy: "direction_plan",
    tools: tools(["propose", "generate"]),
    proposeScene: "ip-propose",
    generateScene: "t2i-associate",
    output: "image",
    steps: ["clarify", "confirm_plan", "generate Logo"],
    isDefault: true,
  },
  {
    id: "skill.image.event",
    name: "活动 · 文生图",
    description: "活动海报/物料文生图：成图类型+画面描述 → t2i-event 出图",
    specialistId: "image.event",
    workbench: wb("image", "event"),
    triggerKeywords: ["活动", "海报", "长图", "易拉宝", "宣传单", "文生图"],
    requiredSlotKeys: ["format", "theme"],
    exits: ["propose", "generate"],
    gatePolicy: "direction_plan",
    tools: tools(["propose", "generate"]),
    proposeScene: "t2i-associate",
    generateScene: "t2i-event",
    output: "image",
    steps: ["clarify", "propose", "confirm_plan", "generate"],
    isDefault: true,
  },
  {
    id: "skill.image.event_i2i",
    name: "活动 · 图生图",
    description: "活动图生图：上传参考图 + 图片描述 → 方向提案 → 图生图",
    specialistId: "image.event",
    workbench: wb("image", "event"),
    triggerKeywords: ["图生图", "改图", "相似图", "改尺寸"],
    requiredSlotKeys: ["theme"],
    exits: ["propose", "generate"],
    gatePolicy: "direction_plan",
    tools: tools(["propose", "generate"]),
    proposeScene: "t2i-associate",
    generateScene: "t2i-event",
    output: "image",
    steps: ["上传参考图", "填写图片描述", "propose", "confirm_plan", "generate"],
    when: { slot: "pipeline", equals: "图生图" },
  },
  {
    id: "skill.image.product_bg",
    name: "商拍 · 商品换背景",
    description: "商拍换背景（aiscene）：商品图 + 场景预设 → t2i-product",
    specialistId: "image.product",
    workbench: wb("image", "product"),
    triggerKeywords: ["商拍", "换背景", "商品换背景", "电商主图"],
    requiredSlotKeys: ["bgMode", "scene"],
    exits: ["generate"],
    gatePolicy: "ref_image",
    tools: tools(["generate"]),
    generateScene: "t2i-product",
    output: "image",
    steps: ["上传商品图", "选场景", "generate"],
    when: { slot: "bgMode", equals: "商品换背景" },
    isDefault: true,
  },
  /** 兼容旧 id → 与 product_bg 同定义，resolve 时归一 */
  {
    id: "skill.image.product",
    name: "商拍 · 商品换背景（兼容）",
    description: "兼容旧 SkillId，等同 skill.image.product_bg",
    specialistId: "image.product",
    workbench: wb("image", "product"),
    triggerKeywords: ["商拍", "商品图"],
    requiredSlotKeys: ["scene"],
    exits: ["generate"],
    gatePolicy: "ref_image",
    tools: tools(["generate"]),
    generateScene: "t2i-product",
    output: "image",
    steps: ["同 product_bg"],
  },
  {
    id: "skill.image.product_multi",
    name: "商拍 · 多角度",
    description: "商品多角度展示图：须商品参考图",
    specialistId: "image.product",
    workbench: wb("image", "product"),
    triggerKeywords: ["多角度", "多视角", "360"],
    requiredSlotKeys: ["bgMode"],
    exits: ["generate"],
    gatePolicy: "ref_image",
    tools: tools(["generate"]),
    generateScene: "t2i-product",
    output: "image",
    steps: ["上传商品图", "generate 多角度"],
    when: { slot: "bgMode", equals: "多角度" },
  },
  {
    id: "skill.image.product_cutwhite",
    name: "商拍 · 抠图白底",
    description: "商品抠图白底主图",
    specialistId: "image.product",
    workbench: wb("image", "product"),
    triggerKeywords: ["抠图白底", "白底图", "抠白"],
    requiredSlotKeys: ["bgMode"],
    exits: ["generate"],
    gatePolicy: "ref_image",
    tools: tools(["generate"]),
    generateScene: "t2i-product",
    output: "image",
    steps: ["上传商品图", "generate 白底"],
    when: { slot: "bgMode", equals: "抠图白底" },
  },
  {
    id: "skill.image.product_transparent",
    name: "商拍 · 透明底",
    description: "商品抠图透明底",
    specialistId: "image.product",
    workbench: wb("image", "product"),
    triggerKeywords: ["透明底", "透明背景", "PNG抠图"],
    requiredSlotKeys: ["bgMode"],
    exits: ["generate"],
    gatePolicy: "ref_image",
    tools: tools(["generate"]),
    generateScene: "t2i-product",
    output: "image",
    steps: ["上传商品图", "generate 透明底"],
    when: { slot: "bgMode", equals: "透明底" },
  },
  {
    id: "skill.image.product_color",
    name: "商拍 · 抠图色底",
    description: "商品抠图纯色背景",
    specialistId: "image.product",
    workbench: wb("image", "product"),
    triggerKeywords: ["抠图色底", "色底", "纯色背景"],
    requiredSlotKeys: ["bgMode"],
    exits: ["generate"],
    gatePolicy: "ref_image",
    tools: tools(["generate"]),
    generateScene: "t2i-product",
    output: "image",
    steps: ["上传商品图", "选色", "generate"],
    when: { slot: "bgMode", equals: "抠图色底" },
  },
  {
    id: "skill.image.product_scene",
    name: "商拍 · 场景底",
    description: "商品融入指定场景底图",
    specialistId: "image.product",
    workbench: wb("image", "product"),
    triggerKeywords: ["场景底", "场景融合", "产地场景"],
    requiredSlotKeys: ["bgMode", "scene"],
    exits: ["generate"],
    gatePolicy: "ref_image",
    tools: tools(["generate"]),
    generateScene: "t2i-product",
    output: "image",
    steps: ["上传商品图", "选场景", "generate"],
    when: { slot: "bgMode", equals: "场景底" },
  },
  {
    id: "skill.image.signage",
    name: "店招 · 线上店招",
    description: "电商/线上店铺横幅店招",
    specialistId: "image.signage",
    workbench: wb("image", "signage"),
    triggerKeywords: ["店招", "线上店招", "店铺横幅"],
    requiredSlotKeys: ["channel", "shopName"],
    exits: ["generate"],
    gatePolicy: "direction_plan",
    tools: tools(["generate"]),
    generateScene: "t2i-associate",
    output: "image",
    steps: ["clarify", "confirm_plan", "generate"],
    when: { slot: "channel", equals: "线上店招" },
    isDefault: true,
  },
  {
    id: "skill.image.signage_storefront",
    name: "店招 · 实体门头",
    description: "线下实体店门头/招牌设计",
    specialistId: "image.signage",
    workbench: wb("image", "signage"),
    triggerKeywords: ["门头", "实体门头", "线下招牌"],
    requiredSlotKeys: ["channel", "shopName"],
    exits: ["generate"],
    gatePolicy: "direction_plan",
    tools: tools(["generate"]),
    generateScene: "t2i-associate",
    output: "image",
    steps: ["clarify", "confirm_plan", "generate 门头"],
    when: { slot: "channel", equals: "实体门头" },
  },
  {
    id: "skill.image.font",
    name: "AI 字体",
    description: "艺术字标题：文字与效果分类确认后出图",
    specialistId: "image.font",
    workbench: wb("image", "font"),
    triggerKeywords: ["字体", "艺术字", "标题字", "字效"],
    requiredSlotKeys: ["text"],
    exits: ["generate"],
    gatePolicy: "direction_plan",
    tools: tools(["generate"]),
    generateScene: "t2i-associate",
    output: "image",
    steps: ["clarify", "confirm_plan", "generate"],
    isDefault: true,
  },

  // ═══════════════════ 文案 /content ═══════════════════
  {
    id: "skill.content.social_wechat",
    name: "社媒推文 · 微信朋友圈",
    description:
      "社媒·微信朋友圈：产品/人群/优势 + 可选大纲（主标题/副标题/关键词）→ social 朋友圈正文",
    specialistId: "content.social",
    workbench: wb("content", "social"),
    triggerKeywords: ["朋友圈", "微信朋友圈", "微信推文"],
    requiredSlotKeys: ["topic", "audience"],
    exits: ["propose", "generate"],
    gatePolicy: "none",
    tools: tools(["propose", "generate"]),
    proposeScene: "social",
    generateScene: "social",
    output: "text",
    steps: ["clarify 产品/人群", "可选大纲", "generate 朋友圈文案"],
    when: { slot: "platform", equals: "微信朋友圈" },
    isDefault: true,
  },
  {
    id: "skill.content.social_xhs",
    name: "社媒推文 · 小红书",
    description:
      "社媒·小红书：产品/人群/优势 + 可选大纲（主标题/副标题/关键词）→ social 笔记标题正文标签",
    specialistId: "content.social",
    workbench: wb("content", "social"),
    triggerKeywords: ["小红书", "种草", "笔记"],
    requiredSlotKeys: ["topic", "audience"],
    exits: ["propose", "generate"],
    gatePolicy: "none",
    tools: tools(["propose", "generate"]),
    proposeScene: "social",
    generateScene: "social",
    output: "text",
    steps: ["clarify 产品/人群", "可选大纲", "generate 小红书笔记"],
    when: { slot: "platform", equals: "小红书" },
  },
  /** 兼容旧 id → 按 platform 解析；未选平台时等同朋友圈 */
  {
    id: "skill.content.social",
    name: "社媒推文（兼容）",
    description: "兼容旧 SkillId；解析时按 platform 落到微信/小红书",
    specialistId: "content.social",
    workbench: wb("content", "social"),
    triggerKeywords: ["社媒", "推文"],
    requiredSlotKeys: ["topic", "audience"],
    exits: ["propose", "generate"],
    gatePolicy: "none",
    tools: tools(["propose", "generate"]),
    proposeScene: "social",
    generateScene: "social",
    output: "text",
    steps: ["同 social_wechat / social_xhs"],
  },
  {
    id: "skill.content.official",
    name: "公众号帮写",
    description:
      "微信公众号长文：标题/关键词/大纲 → 结构清晰的纯文本正文（无 Markdown，可粘贴后台）",
    specialistId: "content.official",
    workbench: wb("content", "official"),
    triggerKeywords: ["公众号", "长文", "微信排版", "公众号文章", "推文长文"],
    requiredSlotKeys: ["topic"],
    exits: ["generate"],
    gatePolicy: "none",
    tools: tools(["generate"]),
    generateScene: "official",
    output: "text",
    steps: ["clarify", "generate official（微信友好结构）"],
    isDefault: true,
  },
  {
    id: "skill.content.brand",
    name: "品牌推广",
    description: "品牌推广文案：卖点/人群 → brand",
    specialistId: "content.brand",
    workbench: wb("content", "brand"),
    triggerKeywords: ["品牌文案", "推广文案", "卖点文案"],
    requiredSlotKeys: ["brand", "sellingPoints"],
    exits: ["generate"],
    gatePolicy: "none",
    tools: tools(["generate"]),
    generateScene: "brand",
    output: "text",
    steps: ["clarify", "generate brand"],
    isDefault: true,
  },

  // ═══════════════════ 视频 /video ═══════════════════
  {
    id: "skill.video.oneline",
    name: "一句话成片 · 文生视频",
    description: "一句话成片文生视频：先出分镜/画面文案 Brief",
    specialistId: "video.oneline",
    workbench: wb("video", "oneline"),
    triggerKeywords: ["一句话", "文生视频", "快速成片", "短视频"],
    requiredSlotKeys: ["oneLiner"],
    exits: ["generate"],
    gatePolicy: "none",
    tools: tools(["generate"]),
    generateScene: "t2i-associate",
    output: "text",
    steps: ["clarify", "generate 分镜文案"],
    when: { slot: "pipeline", equals: "文生视频" },
    isDefault: true,
  },
  {
    id: "skill.video.oneline_i2v",
    name: "一句话成片 · 图生视频",
    description: "一句话成片图生视频：须参考图，先出图生视频 Brief",
    specialistId: "video.oneline",
    workbench: wb("video", "oneline"),
    triggerKeywords: ["图生视频", "首帧成片", "图转动画"],
    requiredSlotKeys: ["oneLiner"],
    exits: ["generate"],
    gatePolicy: "ref_image",
    tools: tools(["generate"]),
    generateScene: "t2i-associate",
    output: "text",
    steps: ["上传参考图", "clarify", "generate 图生视频 Brief"],
    when: { slot: "pipeline", equals: "图生视频" },
  },
  {
    id: "skill.video.avatar",
    name: "数字人模特",
    description: "数字人口播稿：可提案再生成 avatar-script",
    specialistId: "video.avatar",
    workbench: wb("video", "avatar"),
    triggerKeywords: ["数字人", "口播", "主播", "出镜"],
    requiredSlotKeys: ["script"],
    exits: ["propose", "generate"],
    gatePolicy: "none",
    tools: tools(["propose", "generate"]),
    proposeScene: "avatar-script",
    generateScene: "avatar-script",
    output: "text",
    steps: ["clarify", "propose/generate 口播稿"],
    isDefault: true,
  },
  {
    id: "skill.video.studio",
    name: "制作大片 · 脚本编辑",
    description: "制作大片第一步：Brief → studio-script",
    specialistId: "video.studio",
    workbench: wb("video", "studio"),
    triggerKeywords: ["大片", "宣传片", "脚本", "剧本", "制作大片"],
    requiredSlotKeys: ["brief"],
    exits: ["generate"],
    gatePolicy: "none",
    tools: tools(["generate"]),
    generateScene: "studio-script",
    output: "text",
    steps: ["clarify Brief", "generate studio-script"],
    when: { slot: "studioStep", equals: "脚本编辑" },
    isDefault: true,
  },
  {
    id: "skill.video.studio_assets",
    name: "制作大片 · 角色场景道具",
    description: "制作大片第二步：角色/场景/道具资产描述",
    specialistId: "video.studio",
    workbench: wb("video", "studio"),
    triggerKeywords: ["角色场景", "道具", "资产", "人物设定"],
    requiredSlotKeys: ["brief"],
    exits: ["generate"],
    gatePolicy: "none",
    tools: tools(["generate"]),
    generateScene: "studio-assets",
    output: "text",
    steps: ["基于脚本", "generate studio-assets"],
    when: { slot: "studioStep", equals: "角色场景道具" },
  },
  {
    id: "skill.video.studio_storyboard",
    name: "制作大片 · 分镜制作",
    description: "制作大片第三步：分镜/镜头表",
    specialistId: "video.studio",
    workbench: wb("video", "studio"),
    triggerKeywords: ["分镜", "镜头", "storyboard"],
    requiredSlotKeys: ["brief"],
    exits: ["generate"],
    gatePolicy: "none",
    tools: tools(["generate"]),
    generateScene: "studio-shots",
    output: "text",
    steps: ["基于脚本与资产", "generate studio-shots"],
    when: { slot: "studioStep", equals: "分镜制作" },
  },
  {
    id: "skill.video.studio_preview",
    name: "制作大片 · 视频预览",
    description: "制作大片第四步：成片摘要与预览说明（对话内给摘要）",
    specialistId: "video.studio",
    workbench: wb("video", "studio"),
    triggerKeywords: ["视频预览", "成片预览", "大片预览"],
    requiredSlotKeys: ["brief"],
    exits: ["generate"],
    gatePolicy: "none",
    tools: tools(["generate"]),
    generateScene: "studio-summary",
    output: "text",
    steps: ["汇总脚本/分镜", "generate studio-summary"],
    when: { slot: "studioStep", equals: "视频预览" },
  },

  // ═══════════════════ 调研 /research ═══════════════════
  {
    id: "skill.research.brand",
    name: "品牌市场调研",
    description: "品牌调研报告 research-brand",
    specialistId: "research.brand",
    workbench: wb("research", "brand"),
    triggerKeywords: ["品牌调研", "竞品", "市场调研"],
    requiredSlotKeys: ["brand"],
    exits: ["generate"],
    gatePolicy: "none",
    tools: tools(["generate"]),
    generateScene: "research-brand",
    output: "text",
    steps: ["clarify", "generate"],
    isDefault: true,
  },
  {
    id: "skill.research.industry",
    name: "产业调研专家",
    description:
      "产业投资分析 / TAM·SAM·SOM / 竞争格局 / 定价敏感度；数据须可溯源，输出九模块或专项报告",
    specialistId: "research.industry",
    workbench: wb("research", "industry"),
    triggerKeywords: [
      "产业调研",
      "产业链",
      "投资分析",
      "市场规模",
      "TAM",
      "SAM",
      "SOM",
      "竞争分析",
      "可行性报告",
      "行业研究",
      "定价分析",
      "政策补贴",
    ],
    requiredSlotKeys: ["industry"],
    exits: ["generate"],
    gatePolicy: "none",
    tools: tools(["generate"]),
    generateScene: "research-industry",
    output: "text",
    steps: ["clarify", "选报告类型", "generate research-industry"],
    isDefault: true,
  },
  {
    id: "skill.research.hotsale",
    name: "爆款分析",
    description: "爆款分析报告 research-hotsale",
    specialistId: "research.hotsale",
    workbench: wb("research", "hotsale"),
    triggerKeywords: ["爆款", "爆款分析", "畅销"],
    requiredSlotKeys: ["category"],
    exits: ["generate"],
    gatePolicy: "none",
    tools: tools(["generate"]),
    generateScene: "research-hotsale",
    output: "text",
    steps: ["clarify", "generate"],
    isDefault: true,
  },

  // ═══════════════════ 模版 / 仓库 ═══════════════════
  {
    id: "skill.template.apply",
    name: "模版套用",
    description: "按需求推荐模版方向，引导在对话继续创作",
    workbench: wb("template"),
    triggerKeywords: ["模版", "模板", "套用模版"],
    requiredSlotKeys: [],
    exits: [],
    gatePolicy: "none",
    tools: ["memory_read"],
    output: "guide",
    steps: ["理解意图", "推荐品类", "引导创作"],
  },
  {
    id: "skill.storage.works",
    name: "仓库 · 我的作品",
    description: "回忆/引用我的作品线索，用于继续创作",
    workbench: wb("storage", undefined, "tab=works"),
    triggerKeywords: ["我的作品", "作品库", "历史作品"],
    requiredSlotKeys: [],
    exits: [],
    gatePolicy: "none",
    tools: ["memory_read"],
    output: "guide",
    steps: ["说明可从仓库打开作品", "引导继续创作"],
  },
  {
    id: "skill.storage.materials",
    name: "仓库 · 我的素材",
    description: "回忆/引用素材库线索",
    workbench: wb("storage", undefined, "tab=materials"),
    triggerKeywords: ["我的素材", "素材库", "参考素材"],
    requiredSlotKeys: [],
    exits: [],
    gatePolicy: "none",
    tools: ["memory_read"],
    output: "guide",
    steps: ["说明素材用途", "引导上传附件继续创作"],
  },
  {
    id: "skill.storage.brand",
    name: "账户 · 品牌资产",
    description: "读取品牌记忆事实，注入后续创作填槽",
    workbench: wb("account", undefined, "tab=creations"),
    triggerKeywords: ["品牌资产", "品牌记忆", "品牌库"],
    requiredSlotKeys: [],
    exits: [],
    gatePolicy: "none",
    tools: ["memory_read", "memory_write"],
    output: "guide",
    steps: ["memory_read", "摘要品牌事实"],
  },
];

export const SKILL_BY_ID: Record<string, SkillDef> = Object.fromEntries(
  SKILL_CATALOG.map((s) => [s.id, s])
);

/** 专家 → 默认 Skill（跳过兼容别名 product） */
export const DEFAULT_SKILL_BY_SPECIALIST: Partial<Record<SpecialistId, SkillDef>> = {};
for (const s of SKILL_CATALOG) {
  if (s.specialistId && s.isDefault) {
    DEFAULT_SKILL_BY_SPECIALIST[s.specialistId] = s;
  }
}
