import type { SpecialistDef, SpecialistId } from "./types";

/** 专家注册表：每组 2 个相关问题同轮询问（参考 Miora） */
export const SPECIALISTS: SpecialistDef[] = [
  {
    id: "image.ip",
    label: "品牌设计 · IP设计",
    keywords: ["ip", "IP", "吉祥物", "形象", "表情包", "拟人"],
    route: { view: "image", sub: "ip" },
    greet: "好呀！我来帮你做品牌 IP。下面按功能页来问：创意描述、偏好颜色、画面尺寸、参考图。",
    exits: ["propose", "generate"],
    handoffLabel: "在对话中完成",
    slots: [
      {
        key: "mode",
        label: "创作方式",
        priority: 3,
        ask: "走「IP创新设计」还是「IP扩展设计」？（与功能页顶栏一致）",
        options: ["创新设计", "扩展设计"],
        extractHints: ["创新", "从零", "新建", "扩展", "延展", "已有"],
        defaultValue: "创新设计",
        mapsToForm: "designTab",
        group: 0,
      },
      {
        key: "creativeDesc",
        label: "创意描述",
        priority: 1,
        ask: "创意描述点选一条，或「我自己写」（对齐功能页必填「创意描述」）：",
        options: [
          "稻小金——金色稻穗拟人，斗笠汉服，丰收喜悦",
          "茶小芽——嫩绿茶芽姑娘，草本清新",
          "果蔬拟人吉祥物——圆润可爱，品牌主视觉",
          "小动物IP——圆眼弯眉，憨厚可亲",
          "我自己写",
        ],
        extractHints: ["拟人", "吉祥物", "稻", "茶", "动物", "汉服", "斗笠"],
        mapsToForm: "desc",
        group: 1,
        when: { slot: "mode", equals: "创新设计" },
      },
      {
        key: "colors",
        label: "偏好颜色",
        priority: 1,
        ask: "偏好颜色点选（对齐功能页「偏好颜色」）：",
        options: ["自然草本绿", "国潮红金", "柔粉可爱", "轻奢黑金", "你定"],
        extractHints: ["绿", "红", "粉", "金", "黑", "国潮"],
        defaultValue: "自然草本绿",
        mapsToForm: "colors",
        group: 1,
        when: { slot: "mode", equals: "创新设计" },
      },
      {
        key: "ratio",
        label: "画面尺寸",
        priority: 1,
        ask: "画面尺寸点选（对齐功能页「画面尺寸」）：",
        options: ["正方形 1:1", "纵向 3:5", "横向 5:3", "宽屏 16:9"],
        extractHints: ["1:1", "3:5", "5:3", "16:9", "方形", "竖", "横"],
        defaultValue: "正方形 1:1",
        mapsToForm: "ratio",
        group: 2,
        when: { slot: "mode", equals: "创新设计" },
      },
      {
        key: "refHint",
        label: "参考图",
        priority: 2,
        ask: "要上传参考图吗？（对齐功能页「参考」；可选）",
        options: ["暂不上传", "我已上传参考图"],
        extractHints: ["参考", "上传"],
        defaultValue: "暂不上传",
        mapsToForm: "reference",
        group: 2,
        when: { slot: "mode", equals: "创新设计" },
      },
      {
        key: "extendType",
        label: "延展项",
        priority: 1,
        ask: "延展哪一类？（对应功能页：视角/场景/动作/表情/服装）",
        options: ["视角", "场景", "动作", "表情", "服装"],
        extractHints: ["视角", "场景", "动作", "表情", "服装"],
        defaultValue: "场景",
        mapsToForm: "extendType",
        group: 1,
        when: { slot: "mode", equals: "扩展设计" },
      },
      {
        key: "ipImage",
        label: "上传 IP 图",
        priority: 1,
        ask: "请点附件上传已有 IP 图。（对应功能页「上传 IP 图」）",
        options: ["我已上传", "改成创新设计"],
        extractHints: [],
        mapsToForm: "ipImage",
        group: 1,
        when: { slot: "mode", equals: "扩展设计" },
      },
    ],
  },
  {
    id: "image.logo",
    label: "品牌设计 · logo",
    keywords: ["logo", "标志", "商标", "LOGO"],
    route: { view: "image", sub: "logo" },
    greet: "好的，做 Logo。尽量点选，少打字。",
    exits: ["generate"],
    handoffLabel: "在对话中完成",
    slots: [
      {
        key: "brandName",
        label: "品牌名称",
        priority: 1,
        ask: "品牌名称选一个，或点「我自己写」：",
        options: ["安吉白茶", "樱桃", "云间茶舍", "稻小金", "我自己写"],
        extractHints: [],
        mapsToForm: "brand",
        group: 1,
      },
      {
        key: "style",
        label: "logo 风格",
        priority: 1,
        ask: "logo 风格点选：",
        options: ["智能匹配", "图文插画", "图文简约", "文字logo", "字母logo", "经典徽章", "新中式"],
        extractHints: ["智能", "插画", "简约", "文字", "字母", "徽章", "新中式", "国潮", "中国风"],
        defaultValue: "智能匹配",
        mapsToForm: "style",
        group: 1,
      },
      {
        key: "creativeDesc",
        label: "创意描述",
        priority: 2,
        ask: "创意描述要补充吗？点选即可：",
        options: [
          "无特殊要求",
          "以茶叶/山雾元素为主，清新国风",
          "以果实/丰收元素为主，亲和可爱",
          "极简文字为主，现代高级",
          "我自己写",
        ],
        extractHints: [],
        defaultValue: "无特殊要求",
        mapsToForm: "input",
        group: 2,
      },
    ],
  },
  {
    id: "image.event",
    label: "品牌设计 · 活动",
    keywords: ["活动", "海报", "长图", "菜单", "价目", "易拉宝", "展架", "宣传单", "传单", "单页", "上市", "价签", "展板"],
    route: { view: "image", sub: "event" },
    greet: "好的，做活动视觉。下面直接点选就行。",
    exits: ["propose", "generate"],
    handoffLabel: "在对话中完成",
    slots: [
      {
        key: "pipeline",
        label: "生成方式",
        priority: 2,
        ask: "走「文生图」还是「图生图」？（与活动工作台一致）",
        options: ["文生图", "图生图"],
        extractHints: ["文生图", "图生图", "改图", "相似图"],
        defaultValue: "文生图",
        mapsToForm: "pipeline",
        group: 1,
      },
      {
        key: "refUpload",
        label: "参考图",
        priority: 1,
        ask: "图生图需要参考图：请先点下方输入框旁的附件上传图片，上传完成后再点选：",
        options: ["我已上传参考图", "改成文生图"],
        extractHints: [],
        mapsToForm: "reference",
        group: 0,
        when: { slot: "pipeline", equals: "图生图" },
      },
      {
        key: "format",
        label: "成图类型",
        priority: 1,
        ask: "成图类型点选：",
        options: ["海报", "长图", "易拉宝", "宣传单", "菜单"],
        extractHints: ["海报", "长图", "易拉宝", "宣传单", "菜单", "传单"],
        defaultValue: "海报",
        mapsToForm: "sub",
        group: 1,
        when: { slot: "pipeline", equals: "文生图" },
      },
      {
        key: "theme",
        label: "画面描述",
        priority: 1,
        ask: "海报用途和画面内容点选一条（也可自定义输入）：",
        options: [
          "春茶上市 · 山雾茶园 · 主标题「明前新茶」",
          "丰收节庆 · 红金配色 · 主标题「丰收喜乐」",
          "文旅打卡 · 水墨山水 · 主标题「诗画家乡」",
          "开业大吉 · 醒目大字 · 主标题「开业盛典」",
          "非遗手作 · 匠心器物 · 主标题「匠心传承」",
          "特产促销 · 新鲜诱人 · 主标题「产地直发」",
          "我自己写",
        ],
        extractHints: ["上市", "开业", "促销", "丰收", "节庆", "文旅"],
        defaultValue: "春茶上市 · 山雾茶园 · 主标题「明前新茶」",
        mapsToForm: "input",
        group: 1,
      },
      {
        key: "style",
        label: "画面风格",
        priority: 2,
        ask: "画面风格点选：",
        options: ["智能匹配", "国潮", "水彩", "扁平矢量", "卡通动漫", "线描", "版画", "写实摄影", "纹样"],
        extractHints: ["国潮", "水彩", "扁平", "卡通", "线描", "版画", "摄影", "写实", "纹样", "中国风", "国风", "中国风格"],
        defaultValue: "智能匹配",
        mapsToForm: "style",
        group: 2,
      },
      {
        key: "ratio",
        label: "图片尺寸",
        priority: 2,
        ask: "图片尺寸点选：",
        options: ["竖版3:4", "竖版9:16", "横版16:9", "方版1:1", "你定"],
        extractHints: ["3:4", "9:16", "16:9", "1:1", "竖", "横", "方"],
        defaultValue: "竖版3:4",
        mapsToForm: "ratio",
        group: 2,
      },
    ],
  },
  {
    id: "image.product",
    label: "品牌设计 · 商拍",
    keywords: ["商拍", "电商", "主图", "详情页", "白底", "商品图", "换背景", "抠图"],
    route: { view: "image", sub: "product" },
    greet: "好的，商拍出图。先选换底模式，再上传商品图。",
    exits: ["generate"],
    handoffLabel: "在对话中完成",
    slots: [
      {
        key: "bgMode",
        label: "换底模式",
        priority: 1,
        ask: "商拍模式点选（对齐工作台换底）：",
        options: ["商品换背景", "多角度", "抠图白底", "透明底", "抠图色底", "场景底"],
        extractHints: ["换背景", "多角度", "白底", "透明", "色底", "场景底", "抠图"],
        defaultValue: "商品换背景",
        mapsToForm: "bgMode",
        group: 0,
      },
      {
        key: "productImage",
        label: "商品实拍",
        priority: 1,
        ask: "先上传商品实拍/包装图，再点选：",
        options: ["我已上传，请出图", "稍后再说"],
        extractHints: [],
        mapsToForm: "productImg",
        group: 1,
      },
      {
        key: "scene",
        label: "场景预设",
        priority: 1,
        ask: "场景预设点选（换背景 / 场景底时用）：",
        options: ["纯色场景", "高山茶园", "竹林青石", "稻田秋收", "果园枝头", "农家餐桌", "节日礼赠"],
        extractHints: ["纯色", "白底", "茶园", "竹林", "稻田", "果园", "餐桌", "礼赠"],
        defaultValue: "高山茶园",
        mapsToForm: "scenePreset",
        group: 1,
      },
    ],
  },
  {
    id: "image.signage",
    label: "品牌设计 · 店招设计",
    keywords: ["店招", "门头"],
    route: { view: "image", sub: "signage" },
    greet: "好的，做店招。尽量点选。",
    exits: ["generate"],
    handoffLabel: "在对话中完成",
    slots: [
      {
        key: "channel",
        label: "渠道",
        priority: 1,
        ask: "渠道点选：",
        options: ["线上店招", "实体门头"],
        extractHints: ["线上", "电商", "门头", "实体", "线下"],
        defaultValue: "线上店招",
        mapsToForm: "channel",
        group: 1,
      },
      {
        key: "shopName",
        label: "店铺名称",
        priority: 1,
        ask: "店铺名称点选，或「我自己写」：",
        options: ["安吉白茶旗舰店", "云间茶舍", "樱桃铺子", "稻香人家", "我自己写"],
        extractHints: [],
        mapsToForm: "shopName",
        group: 1,
      },
      {
        key: "industry",
        label: "行业",
        priority: 2,
        ask: "行业点选：",
        options: ["茶叶", "特产生鲜", "餐饮农家乐", "文旅景区", "手作伴手礼"],
        extractHints: ["茶", "生鲜", "特产", "餐饮", "农家", "文旅", "景区", "手作"],
        defaultValue: "茶叶",
        mapsToForm: "industry",
        group: 2,
      },
      {
        key: "style",
        label: "风格",
        priority: 2,
        ask: "风格点选：",
        options: ["新中式", "国潮", "清新产地", "促销爆款", "简约高级"],
        extractHints: ["中式", "国潮", "产地", "促销", "简约", "中国风"],
        defaultValue: "新中式",
        mapsToForm: "style",
        group: 2,
      },
      {
        key: "slogan",
        label: "Slogan / 活动文案",
        priority: 3,
        ask: "Slogan 要点选吗？",
        options: ["暂无", "明前芽茶 · 产地直发", "丰收好礼 · 限时特惠", "我自己写"],
        extractHints: [],
        defaultValue: "暂无",
        mapsToForm: "slogan",
        group: 3,
      },
    ],
  },
  {
    id: "image.font",
    label: "品牌设计 · AI字体",
    keywords: ["字体", "艺术字", "书法字", "标题字"],
    route: { view: "image", sub: "font" },
    greet: "好的，做艺术字。点选为主。",
    exits: ["generate"],
    handoffLabel: "在对话中完成",
    slots: [
      {
        key: "text",
        label: "文字内容",
        priority: 1,
        ask: "文字内容点选，或「我自己写」：",
        options: ["丰收喜乐", "明前新茶", "开业大吉", "匠心传承", "诗画家乡", "我自己写"],
        extractHints: [],
        mapsToForm: "text",
        group: 1,
      },
      {
        key: "dir",
        label: "文字方向",
        priority: 1,
        ask: "文字方向点选：",
        options: ["横向", "竖向"],
        extractHints: ["横", "竖"],
        defaultValue: "横向",
        mapsToForm: "dir",
        group: 1,
      },
      {
        key: "style",
        label: "文字效果分类",
        priority: 2,
        ask: "文字效果分类点选：",
        options: ["书法体", "现代体", "艺术体"],
        extractHints: ["书法", "现代", "艺术"],
        defaultValue: "书法体",
        mapsToForm: "cat",
        group: 2,
      },
    ],
  },
  {
    id: "content.social",
    label: "文案策划 · 社媒推文",
    keywords: ["朋友圈", "小红书", "笔记", "微博", "话题", "推文", "社媒", "文案"],
    route: { view: "content", sub: "social" },
    greet: "好的，写社媒文案。先选平台，再填产品信息；大纲可选。",
    exits: ["propose", "generate"],
    handoffLabel: "在对话中完成",
    slots: [
      {
        key: "platform",
        label: "推广平台",
        priority: 1,
        ask: "平台点选：",
        options: ["微信朋友圈", "小红书"],
        extractHints: ["朋友圈", "微信", "小红书"],
        defaultValue: "微信朋友圈",
        mapsToForm: "platforms",
        group: 0,
      },
      {
        key: "topic",
        label: "产品名",
        priority: 1,
        ask: "产品名点选，或「我自己写」：",
        options: ["安吉白茶", "萧山萝卜干", "杨梅", "蜂蜜", "我自己写"],
        extractHints: [],
        mapsToForm: "product",
        group: 1,
      },
      {
        key: "audience",
        label: "目标人群",
        priority: 1,
        ask: "目标人群点选：",
        options: ["白领职场", "宝妈", "银发族", "学生群体", "健身运动", "户外爱好者"],
        extractHints: ["白领", "宝妈", "银发", "学生", "健身", "户外", "孕妇", "婴幼儿"],
        defaultValue: "白领职场",
        mapsToForm: "audience",
        group: 1,
      },
      {
        key: "brand",
        label: "品牌名",
        priority: 2,
        ask: "品牌名要点选吗？",
        options: ["暂无", "极鲜生", "杨梅叶气", "我自己写"],
        extractHints: [],
        defaultValue: "暂无",
        mapsToForm: "brand",
        group: 2,
      },
      {
        key: "advantage",
        label: "产品优势",
        priority: 2,
        ask: "产品优势要点选吗？（可选）",
        options: ["产地直采", "全程冷链", "0添加", "暂无", "我自己写"],
        extractHints: ["直采", "冷链", "添加", "有机", "新鲜"],
        defaultValue: "暂无",
        mapsToForm: "advantage",
        group: 2,
      },
      {
        key: "outlineTitle",
        label: "大纲·主标题/主题",
        priority: 3,
        ask: "内容大纲·主标题/主题（可选，对齐工作台）：",
        options: ["春茶上市种草", "产地鲜果直达", "周末探店打卡", "跳过大纲", "我自己写"],
        extractHints: [],
        defaultValue: "跳过大纲",
        mapsToForm: "outline.title",
        group: 3,
      },
      {
        key: "outlineSubtitle",
        label: "大纲·副标题/切入点",
        priority: 3,
        ask: "内容大纲·副标题/切入点（可选）：",
        options: ["一口鲜爽回甘", "适合送礼自用", "亲子出游首选", "跳过", "我自己写"],
        extractHints: [],
        defaultValue: "跳过",
        mapsToForm: "outline.subtitle",
        group: 3,
      },
      {
        key: "outlineKeywords",
        label: "大纲·关键词",
        priority: 3,
        ask: "内容大纲·关键词（可选，逗号分隔）：",
        options: ["明前茶,鲜爽", "产地直发,冷链", "周末好去处", "跳过", "我自己写"],
        extractHints: [],
        defaultValue: "跳过",
        mapsToForm: "outline.keywords",
        group: 3,
      },
    ],
  },
  {
    id: "content.official",
    label: "文案策划 · 公众号帮写",
    keywords: ["公众号", "长文", "微信排版", "公众号文章"],
    route: { view: "content", sub: "official" },
    greet: "好的，写公众号长文。尽量点选标题、关键词和风格。",
    exits: ["generate"],
    handoffLabel: "在对话中完成",
    slots: [
      {
        key: "topic",
        label: "文章标题",
        priority: 1,
        ask: "标题方向点选，或「我自己写」：",
        options: [
          "春茶上市指南：如何挑选明前好茶",
          "县域特产出海：品牌故事怎么讲",
          "乡村振兴实践：一片叶子的产业路",
          "我自己写",
        ],
        extractHints: [],
        mapsToForm: "title",
        group: 1,
      },
      {
        key: "keywords",
        label: "核心关键词",
        priority: 1,
        ask: "关键词组合点选：",
        options: [
          "明前茶，产地直发，春茶",
          "乡村振兴，特色农产品，品牌",
          "文旅打卡，非遗，乡土文化",
          "我自己写",
        ],
        extractHints: [],
        mapsToForm: "keywords",
        group: 1,
      },
      {
        key: "style",
        label: "文案风格",
        priority: 2,
        ask: "文案风格点选：",
        options: ["政企风", "娱乐风", "短剧风", "情感文", "干货科普"],
        extractHints: ["政企", "娱乐", "短剧", "情感", "干货", "科普"],
        defaultValue: "干货科普",
        mapsToForm: "style",
        group: 2,
      },
      {
        key: "length",
        label: "字数范围",
        priority: 2,
        ask: "字数点选：",
        options: ["600-800字", "800-1200字", "1200-2000字", "2000字以上"],
        extractHints: ["600", "800", "1200", "2000"],
        defaultValue: "800-1200字",
        mapsToForm: "length",
        group: 2,
      },
    ],
  },
  {
    id: "content.brand",
    label: "文案策划 · 品牌推广",
    keywords: ["推广", "卖点", "主张", "slogan"],
    route: { view: "content", sub: "brand" },
    greet: "好的，做品牌推广文案。点选为主。",
    exits: ["generate"],
    handoffLabel: "在对话中完成",
    slots: [
      {
        key: "brand",
        label: "品牌名称及产品类型",
        priority: 1,
        ask: "品牌/产品点选，或「我自己写」：",
        options: ["极鲜生 · 南美白对虾", "安吉白茶 · 明前芽茶", "樱桃铺子 · 时令鲜果", "我自己写"],
        extractHints: [],
        mapsToForm: "product",
        group: 1,
      },
      {
        key: "audience",
        label: "目标市场/人群",
        priority: 1,
        ask: "目标人群点选：",
        options: ["一二线白领 · 健康饮食", "亲子家庭 · 伴手礼", "银发族 · 滋补养生", "我自己写"],
        extractHints: ["白领", "亲子", "银发", "养生"],
        defaultValue: "一二线白领 · 健康饮食",
        mapsToForm: "audience",
        group: 1,
      },
      {
        key: "sellingPoints",
        label: "产品核心优势",
        priority: 1,
        ask: "核心优势点选：",
        options: [
          "产地直采，全程冷链，0添加",
          "明前采摘，一芽一叶，香气清雅",
          "当日达鲜，坏果包赔",
          "我自己写",
        ],
        extractHints: [],
        mapsToForm: "advantage",
        group: 2,
      },
      {
        key: "goal",
        label: "营销目标",
        priority: 2,
        ask: "营销目标点选：",
        options: ["提升知名度", "促进销量", "新品种草", "暂无"],
        extractHints: ["知名度", "销量", "新品", "种草"],
        defaultValue: "提升知名度",
        mapsToForm: "goal",
        group: 2,
      },
    ],
  },
  {
    id: "video.avatar",
    label: "视频宣传 · 数字人模特",
    keywords: ["数字人", "口播", "主播", "出镜"],
    route: { view: "video", sub: "avatar" },
    greet: "好的，帮你做数字人口播稿。",
    exits: ["propose", "generate"],
    handoffLabel: "在对话中完成",
    slots: [
      {
        key: "script",
        label: "口播文案",
        priority: 1,
        ask: "数字人要说什么？可直接写，或点「帮我写一版」。",
        options: ["帮我写一版", "我自己写"],
        extractHints: [],
        mapsToForm: "script",
        group: 1,
      },
      {
        key: "role",
        label: "形象定位",
        priority: 1,
        ask: "形象定位更偏哪种？",
        options: ["景区导游", "农技推广", "带货主播", "官方播报"],
        extractHints: ["导游", "农技", "带货", "播报", "主播"],
        defaultValue: "农技推广",
        mapsToForm: "role",
        group: 1,
      },
    ],
  },
  {
    id: "video.studio",
    label: "视频宣传 · 制作大片",
    keywords: ["大片", "宣传片", "品牌片", "剧本", "分镜", "制作大片"],
    route: { view: "video", sub: "studio" },
    greet: "好的，先选大片做到哪一步，再把 Brief 说清楚。",
    exits: ["generate"],
    handoffLabel: "在对话中完成",
    slots: [
      {
        key: "studioStep",
        label: "大片步骤",
        priority: 1,
        ask: "制作大片做到哪一步？（对齐工作台）",
        options: ["脚本编辑", "角色场景道具", "分镜制作", "视频预览"],
        extractHints: ["脚本", "角色", "场景", "道具", "分镜", "预览"],
        defaultValue: "脚本编辑",
        mapsToForm: "studioStep",
        group: 0,
      },
      {
        key: "brief",
        label: "核心一句话",
        priority: 1,
        ask: "片子要传达的核心一句话是？",
        extractHints: [],
        mapsToForm: "brief",
        group: 1,
      },
      {
        key: "type",
        label: "片型",
        priority: 1,
        ask: "更接近哪种片型？",
        options: ["品牌宣传", "文旅推介", "产品故事", "活动预热"],
        extractHints: ["品牌", "文旅", "产品", "活动", "预热"],
        defaultValue: "文旅推介",
        mapsToForm: "type",
        group: 1,
      },
    ],
  },
  {
    id: "video.oneline",
    label: "视频宣传 · 一句话成片",
    keywords: ["一句话", "快速成片", "成片", "视频", "短视频", "广告", "介绍片", "文生视频", "图生视频"],
    route: { view: "video", sub: "oneline" },
    greet: "好的，一句话成片。先选文生视频还是图生视频。",
    exits: ["generate"],
    handoffLabel: "在对话中完成",
    slots: [
      {
        key: "pipeline",
        label: "生成方式",
        priority: 1,
        ask: "走「文生视频」还是「图生视频」？",
        options: ["文生视频", "图生视频"],
        extractHints: ["文生视频", "图生视频", "文生", "图生"],
        defaultValue: "文生视频",
        mapsToForm: "pipeline",
        group: 0,
      },
      {
        key: "refUpload",
        label: "参考图",
        priority: 1,
        ask: "图生视频需要参考图：请先点下方输入框旁的附件上传，上传完成后再点选：",
        options: ["我已上传参考图", "改成文生视频"],
        extractHints: [],
        mapsToForm: "reference",
        group: 0,
        when: { slot: "pipeline", equals: "图生视频" },
      },
      {
        key: "oneLiner",
        label: "一句话",
        priority: 1,
        ask: "用一句话说这部片子讲什么？",
        extractHints: [],
        mapsToForm: "script",
        group: 1,
      },
      {
        key: "mood",
        label: "氛围",
        priority: 1,
        ask: "氛围偏好？",
        options: ["清新田园", "热闹促销", "温情故事"],
        extractHints: ["田园", "促销", "温情", "清新"],
        defaultValue: "清新田园",
        mapsToForm: "mood",
        group: 1,
      },
    ],
  },
  {
    id: "research.brand",
    label: "市场调研 · 品牌市场调研",
    keywords: ["品牌调研", "竞品", "市场调研"],
    route: { view: "research", sub: "brand" },
    greet: "好的，帮你做品牌市场调研。",
    exits: ["generate"],
    handoffLabel: "在对话中完成",
    slots: [
      {
        key: "brand",
        label: "品牌",
        priority: 1,
        ask: "要调研哪个品牌？",
        extractHints: [],
        mapsToForm: "brand",
        group: 1,
      },
      {
        key: "market",
        label: "市场",
        priority: 1,
        ask: "对标哪个市场或地区？",
        options: ["本地县域", "全省", "全国", "我补充"],
        extractHints: ["县域", "本地", "全省", "全国"],
        defaultValue: "本地县域",
        mapsToForm: "market",
        group: 1,
      },
    ],
  },
  {
    id: "research.industry",
    label: "市场调研 · 产业调研专家",
    keywords: [
      "产业调研",
      "产业链",
      "投资分析",
      "市场规模",
      "TAM",
      "竞争分析",
      "可行性报告",
      "行业研究",
      "定价分析",
    ],
    route: { view: "research", sub: "industry" },
    greet: "好的，按产业调研专家流程帮你做分析。先确认产业主题，再选报告类型。",
    exits: ["generate"],
    handoffLabel: "在对话中完成",
    slots: [
      {
        key: "industry",
        label: "产业",
        priority: 1,
        ask: "关注哪个产业/品类？",
        extractHints: [],
        mapsToForm: "industry",
        group: 1,
      },
      {
        key: "reportFocus",
        label: "报告类型",
        priority: 1,
        ask: "更需要哪类分析？",
        options: ["完整投资分析报告", "市场规模测算", "竞争格局分析", "定价敏感度分析"],
        extractHints: ["投资", "TAM", "市场规模", "竞争", "定价"],
        defaultValue: "完整投资分析报告",
        mapsToForm: "reportFocus",
        group: 1,
      },
      {
        key: "region",
        label: "地区",
        priority: 2,
        ask: "聚焦哪个地区？",
        options: ["本县域", "全省", "全国", "你定"],
        extractHints: ["县", "省", "全国"],
        defaultValue: "本县域",
        mapsToForm: "region",
        group: 2,
      },
    ],
  },
  {
    id: "research.hotsale",
    label: "市场调研 · 爆款分析",
    keywords: ["爆款", "爆款分析"],
    route: { view: "research", sub: "hotsale" },
    greet: "好的，帮你做爆款分析。",
    exits: ["generate"],
    handoffLabel: "在对话中完成",
    slots: [
      {
        key: "category",
        label: "品类",
        priority: 1,
        ask: "分析哪个品类？",
        extractHints: [],
        mapsToForm: "category",
        group: 1,
      },
      {
        key: "platform",
        label: "平台",
        priority: 1,
        ask: "主要看哪个平台？",
        options: ["抖音", "小红书", "淘宝", "综合"],
        extractHints: ["抖音", "小红书", "淘宝"],
        defaultValue: "综合",
        mapsToForm: "platform",
        group: 1,
      },
    ],
  },
];

export function getSpecialist(id: SpecialistId): SpecialistDef | undefined {
  return SPECIALISTS.find((s) => s.id === id);
}

export function recallSpecialists(text: string): SpecialistDef[] {
  const t = text.toLowerCase();
  const ordered = [...SPECIALISTS].sort((a, b) => {
    const rank = (id: SpecialistId) => {
      if (id === "video.avatar") return 0;
      if (id === "video.studio") return 1;
      if (id === "image.logo") return 2;
      if (id === "image.ip") return 3;
      if (id === "image.signage") return 4;
      if (id === "image.font") return 5;
      if (id === "image.product") return 6;
      if (id === "research.hotsale") return 7;
      if (id === "research.brand") return 8;
      if (id === "research.industry") return 9;
      if (id === "content.official") return 10;
      if (id === "content.brand") return 11;
      if (id === "image.event") return 12;
      if (id === "video.oneline") return 13;
      return 20;
    };
    return rank(a.id) - rank(b.id);
  });

  const hits: SpecialistDef[] = [];
  for (const s of ordered) {
    if (s.keywords.some((k) => t.includes(k.toLowerCase()))) hits.push(s);
  }
  return hits;
}
